### ISSUE TITLE
I have installation  problem 

### ISSUE THREAD

**Issue by hassan957** [appsembler/xblock-video#21]
when I run 3rd command
pip install --process-dependency-links -e "git+https://github.com/appsembler/xblock-video.git@dev#egg=video_xblock"
I get this error 
don't know what to do

  Could not find a tag or branch 'dev', assuming commit.
fatal: ambiguous argument 'dev': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Command "git reset --hard -q dev" failed with error code 128 in /edx/app/edxapp/venvs/edxapp/src/video-xblock

**Comment by bryanlandia** [comment]
@hassan957 Sorry for the late reply here.  It's true, our README was written during the development process.  The `dev` branch is not available on this repo.  Please do instead,

```
pip install --process-dependency-links -e "git+https://github.com/appsembler/xblock-video.git#egg=video_xblock
```
