### ISSUE TITLE
Please make 0.6.0 a release in racoongang GitHub 

### ISSUE THREAD

**Issue by bryanlandia** [appsembler/xblock-video#5]
Sorry, I was making comments on commits in 0.5.0 since I thought it was the last release as shown in Releases in racoongang fork.   I couldn't make an issue on racoongang fork so I made it here :P

**Comment by bryanlandia** [comment]
Maybe I'm wrong here... I see the release/0.6.0 branch but maybe it's not a complete release yet.

**Comment by z4y4ts** [comment]
@bryanlandia sorry, I've re-enabled Issues in our repo.

We're releasing 0.6.0 tomorrow. It's at the code review stage at the moment. 

I'll ping back you here when it's out.

**Comment by bryanlandia** [comment]
@z4y4ts I think I don't have permission to see issues in your repo since I don't see them.

**Comment by z4y4ts** [comment]
Resolved
